### ISSUE TITLE
Generating multiple sprites?

### ISSUE THREAD

**Issue by Dhaulagiri** [bguiz/ember-sprite#11]
With this plugin, is there a way to generate both a retina and non-retina sprite?  It seems like [this line](https://github.com/bguiz/ember-sprite/blob/master/index.js#L19) makes it so you can only pass one `sprite` to the plugin, but maybe I'm missing something?

**Comment by Dhaulagiri** [comment]
Closed by #14

**Comment by bguiz** [comment]
Ah yes, thanks once again for #13
