### ISSUE TITLE
broken compatibility with options.stylesheet?

### ISSUE THREAD

**Issue by brumm** [bguiz/ember-sprite#8]
Hey,
Using the below config snippet, I end up with scss code in my generated css file. Is this a supported use case? It seems like a regression from node-sprite-generator's functionality.
```js
  sprite: {
    debug: true,
    src: [
      'assets/images/*checkbox*.png',
      'assets/images/*radiobutton*.png',
      'assets/images/*nav*.png'
    ],
    spritePath: 'assets/sprite-sheet.png',
    stylesheetPath: 'assets/sprites.scss',
    stylesheet: 'scss',
    stylesheetOptions: {
      prefix: 'icon-',
      spritePath: 'assets/sprite-sheet.png',
      pixelRatio: 2,
    },
    layoutOptions: {
      padding: 2,
    },
    compositor: 'gm'
  }
```

**Comment by bguiz** [comment]
It is outputting SCSS because that is what you have configured it to do.

Take a look at the sample options in the README: https://github.com/bguiz/ember-sprite#configuration

These show what to do if you wish to output CSS.
The relevant part is:

      stylesheetPath: 'assets/sprites.css',
      stylesheet: 'css',

Let me know if this answers your question

**Comment by brumm** [comment]
Hey, thanks for getting back to me.

I assumed that there would be a way to `@import` generated scss variables and mixins from my applications' scss stylesheet. However, the scss code gets merged with the output css. This makes sense for plain css prefixed classes, but not for scss variables and mixins. Am I missing something here?

In my usecase, I can't rely on the generated css classes to use the sprites, I need mixins and variables...

**Comment by bguiz** [comment]
Yeah, in the case of ember-sprite, it does not make any sense to use
anything besides CSS as output.
Take a look at this line:
https://github.com/bguiz/ember-sprite/blob/master/index.js#L34
That's where it explicitly assumes that output is going to be CSS, prior to
merging it.

The option really should be locked down, but I decided against it, because
I wanted power users - whose use cases I do not want to make any
assumptions of - to have the full range of options exposed by
node-sprite-generator available to them, rather than proxying a select
subset of its options.

I'll close this ticket now - I'll reopen if you have any further
suggestions.

W: http://bguiz.com

**Comment by brumm** [comment]
I just revisited this issue. 
As a compromise and workaround, would it be possible to concat the `spriteCssFile` before `appCssFile `? This way, one could use sass' `@extend` to still make use of the generated css classes without having to use them in ones markup.

**Comment by bguiz** [comment]
That would break my own use case, and I suspect that of a few others.
I think that it should stay the way it is by default - `appCssFile`
before `spriteCssFile`.

However, I take your point, that some users might want it to be the
other way around. Perhaps an option could be added that allows you to
switch the concatenation order to the other way around. Does that
sound good to you?

W: http://bguiz.com

**Comment by brumm** [comment]
I erroneously assumed that cross-file extends are possible with Sass, but unfortunetely this is not the case, so including the sprites befor the app css would not actually help me in this case.

However, maybe it would be possible to add an option to skip the merge, and instead drop whatever I configured into `assets/`? I was playing around with this, by simply doing `@import "assets/sprites";`, but it seems like the sprite file is being generated _after_ sass tries to read the file:

```
Error: app/tmp/tree_merger-tmp_dest_dir-FaubeGsj.tmp/app/styles/app.scss:32: error: file to import not found or unreadable: "assets/sprites"
```

**Comment by rosshadden** [comment]
@brumm Did you ever get this working?  I have hit the same situation where I need to import the output sass file so I may use the variables it generates.

/cc @optikalefx

**Comment by brumm** [comment]
unfortunately not, i went ahead and built some `node-sprite-generator` script which requires lots of manual copy and pasting :(
