### ISSUE TITLE
ember-sprite incompatible with broccoli-asset-rev

### ISSUE THREAD

**Issue by mackers** [bguiz/ember-sprite#9]
When I trigger a production build of my ember-cli app like so:

```
ember build -e production
```

I get the following error:

```
Path or pattern "assets/myapp.css" did not match any files
```

This is because the file `myapp.css` has been renamed to `myapp-cbabcba3bcabcb3a3bca3.css` by broccoli-asset-rev.

Therefore ember-sprite cannot complete the css concatenation correctly and the build fails.

**Comment by mackers** [comment]
It's worth noting that I can build successfully if I exclude `myapp.css` from broccoli-asset-rev's fingerprinting process, but that sort of defeats the point!

**Comment by bguiz** [comment]
Hmm, these indicate that broccoli-asset-rev and ember-sprite are
running in the wrong order - ember-sprite needs to run **before**
broccoli-asset-rev does.

I'm not sure what the correct way to ensure that this happen though -
I'll have to have a think about it!
W: http://bguiz.com

**Comment by asleepinglion** [comment]
@bguiz: I ran into this issue over the weekend. What's the best way to resolve this right now?

**Comment by ianpetzer** [comment]
@bguiz @asleepinglion I managed to work around this by putting ember-sprite at the top of my package.json...(or at least before brocolli-asset-rev)

**Comment by bguiz** [comment]
> I managed to work around this by putting ember-sprite at the top of my package.json...(or at least before brocolli-asset-rev)

That's an interesting workaround, which leads me to this as a possible solution:

I vaguely recall something about each ember addon being ableto specify
its pre-req's and post-req's.
That needs to be done within the addons though, not in the consuming app.
Does this ring a bell anyone?
W: http://bguiz.com

**Comment by bguiz** [comment]
@mackers @asleepinglion @ianpetzer See if v0.4.0 - just released today - fixes this for you.

Thanks go to @Dhaulagiri

**Comment by ianpetzer** [comment]
Thanks @Dhaulagiri and @bguiz 

I can confirm this works for me
